# Run docker-compose build
# Run docker-compose up

version: '3.5'

networks:
  default:
    name: web_dev

services:
  server:
    tty: true
    restart: always
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - ENV=development
      - PORT=5000
      - DB=mongodb://mongodb:27017/eyeCloudDB
    depends_on:
      - mongodb
    links:
      - mongodb
  client:
    tty: true
    restart: always
    build: ./client
    volumes:
      - ./client/src:/usr/src/app/src
    ports:
      - "4200:4200"
    depends_on:
      - server
    links:
      - server
   # env_file:
   # - .env
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

